# Generated by Django 3.1.2 on 2021-08-15 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0129_add_product_types_and_attributes_perm'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='whole_sale_price_amount',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
    ]
